
version: '2'

services:
  pg-slave:
    build: '.'
    image: 'terrabrasilis/postgres-replication'
    restart: 'always'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data/pgdata'
      REPLICATE_FROM: '192.168.1.11'
    volumes:
     - '/var/lib/postgresql/data'
    expose:
     - '5432'
